### PR TITLE
GPII-1816: Listeners solution and Visual Studio 2015

### PR DESCRIPTION
**Pull request by minogian**
The CI build uses the Visual Studio 2015 build tools and does not include the listener projects in the build.

### CODE REVIEW

**Comment by javihernandez** [comment]
@minogian thanks for this pull request! 
Since I don't feel like I'm the best person to review this,
@SteveALee can you take a look at the changes on the build chain?
@avtar can you review the changes made on the provisioning system?

**Comment by avtar** [comment]
@javihernandez, @minogian I tried your fork (btw you might be asked to create a GPII-1816 branch for this work) and I was able to test the build successfully. The unit tests fail and stall when the "Testing Killing Processes" test is started but that's a [known issue](https://issues.gpii.net/browse/GPII-1826).

The one thing about this PR though is after the build was completed Bitdefender AntiVirus Plus 2016 (running on Windows 10) alerted me with this message:
```
Bitdefender has detected an infected item in c:\users\avtar\tmp\windows\listeners\bin\release\gpii_usblistener.exe.
Virus name: Gen:Variant.Razy.55883.
```
This seems like a false positive but I'll confirm by submitting the resulting binary to other AV vendors today:
https://virusdesk.kaspersky.com/
https://analysis.avira.com/en/submit

**Comment by avtar** [comment]
I ran the build on another host and uploaded the binary to https://scan.kaspersky.com which reported the file as not being infected. [Screenshot of the result](http://i.imgur.com/NnRHtWH.png). I also [filed a report](http://www.bitdefender.com/submit/) with Bitdefender for the false positive result.

**Comment by SteveALee** [comment]
has to be a false positive if you did the build. Unless your libraries are
infected. :)

Steve Lee
OpenDirective http://opendirective.com

**Comment by minogian** [comment]
I used the latest (7.49.1) source archive from https://curl.haxx.se/download.html to built the cURL .lib files. 
The lib files themselves were not flagged. Probable a false positive.

**Comment by colinbdclark** [comment]
Hi @minogian, easy question for you: which version of the USB and NFC Listeners are these? Are they the original ones written by a contractor hired by RTF-I back in 2012, or are they the newer, awesome ones that were created by @SteveALee? Where did the source code for them come from?

**Comment by minogian** [comment]
Didn't know there was another version of the listeners. 
I updated whatever version is already in the listeners folder in the repository. According to git history the author is @SteveALee.

**Comment by colinbdclark** [comment]
Great, thanks! Just so I'm sure, can you paste me a link to the repository this code is from?

**Comment by minogian** [comment]
I think I'm missing something :-), but here it goes:
https://github.com/GPII/windows/tree/master/listeners

**Comment by colinbdclark** [comment]
Nope, @minogian, it's me! :) I had totally forgotten that these had been merged. Thank you!

**Comment by SteveALee** [comment]
Kasper said the code was merged eventually. Though I don't think the
release was adopted ( i felt they had a separate life cycle)

Steve Lee
Sent from my mobile device Please excuse typing errors
On 4 Jun 2016 22:16, "Colin Clark" <notifications@github.com> wrote:

Hi @minogian <https://github.com/minogian>, easy question for you: which
version of the USB and NFC Listeners are these? Are they the original ones
written by a contractor hired by RTF-I back in 2012, or are they the newer,
awesome ones that were created by @SteveALee <https://github.com/SteveALee>?
Where did the source code for them come from?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/GPII/windows/pull/71#issuecomment-223778761>, or mute
the thread
<https://github.com/notifications/unsubscribe/AAlxqr9taAUIpSOcBARZQyW6XoCWmIwMks5qIesjgaJpZM4IsjNJ>
.

**Comment by SteveALee** [comment]
To complicate matters further Steve Githens created a new RFID listener fir
LGS that works only with some of the builtin hardware which my driver
doesn't work with. We did talk of merging though they are written in c# and
c.

Steve Lee

**Comment by gloob** [comment]
This PR looks good to me, except the inclusion of the generated libcurl_a.lib and libcurl_a_debug.lib files that are generated from the libcurl source code, they should be dropped.

After last merge with the update of our windows toolchain to MSVC2015 this PR fix the listeners build process.

**Comment by minogian** [comment]
The lib files are needed for the build. 
It's either that or we have to include (and build) the full libcurl source code in the CI build.

The current version also includes prebuilt files (https://github.com/GPII/windows/tree/master/listeners/libcurl/lib).

**Comment by SteveALee** [comment]
Sorry for the delay

> @SteveALee <https://github.com/SteveALee> can you take a look at the
changes on the build chain?

Looks fine. Only a couple of version number changes for the tooling.




Steve Lee
OpenDirective http://opendirective.com

**Comment by SteveALee** [comment]
> The lib files are needed for the build. 

The idea was we build and scared between USB and NFC so we had a know versions. Including the curl source is a lazy way of doing it so thanks for updating.

**Comment by avtar** [comment]
@minogian The installer for the listeners appears to [require Inno Setup](https://github.com/minogian/windows/blob/master/listeners/installer/Installer.vcxproj#L32). It's great to see your changes will [make it easier to use](https://github.com/GPII/windows/pull/71/files#diff-44f052772997958cbf7a4737817f01b5R4) within the VM. Could you please add the necessary changes to ``build.bat`` so that a installer [gets built using MSBuild](https://msdn.microsoft.com/en-us/library/dd293607.aspx#Anchor_2) as part of the build process? This will make the CI job that much more useful. Thanks!

**Comment by colinbdclark** [comment]
Other than @avtar's comment, I think this pull request is ready to be merged!

**Comment by SteveALee** [comment]
> The installer for the listeners appears to require Inno Setup

FYI Inno was chosen to give endusers (admins) installing the listeners a decent experience. The assumption was node install was for developers only. We discussed making MSI modules so that enterprises would be happy. Chocolaty, containers etc have made the options even broader now :) The various installation scenarios are yet to be fully analysed as far as I know.

**Comment by minogian** [comment]
@avtar As @SteveALee wrote, the inno setup based installer is provided as an alternative for installing just the listeners. The [full installer](https://github.com/GPII/gpii-wix-installer) is msbuild/wix based and doesn't need inno. I had to update the whole listener solution anyway, so I updated the inno setup project as well.

@avtar & @colinbdclark Building the installer as part of the CI build is definitely a goal (see [GPII-1731](https://issues.gpii.net/browse/GPII-1731)) and I already have a pull request ready for the installer project as soon as this one is merged. Then I can open another one for resolving [GPII-1731](https://issues.gpii.net/browse/GPII-1731).
So, I think you should merge this one (and close [GPII-1816](https://issues.gpii.net/browse/GPII-1816)) and I will open a new pull request, specifically for [GPII-1731](https://issues.gpii.net/browse/GPII-1731)

**Comment by colinbdclark** [comment]
Hey @minogian, if we don't need inno, and you don't think it's worth bothering building the inno-based standalone installer, and you're about to replace it with a new installer, then why is it still included in the repo and configured as part of the build? We should either continuously integrate it or remove it.

**Comment by minogian** [comment]
@colinbdclark I actually said that updating the listeners-only, inno-based setup was very straightforward since I had to update the whole listeners solution anyway.
The [full installer](https://github.com/GPII/gpii-wix-installer) does not need inno but there is almost zero cost in keeping in parallel an updated inno-based setup - just for the listeners - for whoever might need that.

**Comment by colinbdclark** [comment]
I'm sorry, @minogian, much of my line of questioning was caused by confusion about how this system works. I'm not a Windows developer, and it wasn't clear that the listener installer actually gets built automatically as part of the msbuild phase that you added. Thank you for that. I've tested and merged your pull request.

I still think, in general, we need to get rid of anything in the system that isn't being actively tested and used. If your plan with the new WiX installer is to distribute the user listeners along with the rest of the GPII (which is a good idea), then when it's ready we should delete the Inno-based standalone installer for the Listeners. I can't think of who, concretely, the "whoever might need that" is, especially if the WiX installer will provide the ability for users to choose to omit one or more of the listeners.

I've [filed a JIRA about removing the old Listeners installer](
https://issues.gpii.net/browse/GPII-1851), and we can tackle it later when the new installer is ready to be merged.

**Comment by SteveALee** [comment]
If recall the issue is to minimise what gets installed. It was felt some
would object on security grounds which is understandable.

If the listeners are not going to be used why install them? The discussion
was of a range of small targeted listeners each individually installable
rather than a single monolith covering all possibilities

Steve Lee
Sent from my mobile device Please excuse typing errors
On 17 Jun 2016 23:56, "Colin Clark" <notifications@github.com> wrote:

I'm sorry, @minogian <https://github.com/minogian>, much of my line of
questioning was caused by confusion about how this system works. I'm not a
Windows developer, and it wasn't clear that the listener installer actually
gets built automatically as part of the msbuild phase that you added. Thank
you for that. I've tested and merged your pull request.

I still think, in general, we need to get rid of anything in the system
that isn't being actively tested and used. If your plan with the new WiX
installer is to distribute the user listeners along with the rest of the
GPII (which is a good idea), then when it's ready we should delete the
Inno-based standalone installer for the Listeners. I can't think of who,
concretely, the "whoever might need that" is, especially if the WiX
installer will provide the ability for users to choose to omit one or more
of the listeners.

I've filed a JIRA about removing the old Listeners installer
<https://issues.gpii.net/browse/GPII-1851>, and we can tackle it later when
the new installer is ready to be merged.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/GPII/windows/pull/71#issuecomment-226900202>, or mute
the thread
<https://github.com/notifications/unsubscribe/AAlxqvOEUf5O_uey69t1-7Z72oDTDWDUks5qMyYFgaJpZM4IsjNJ>
.

**Comment by cstrobbe** [comment]
By the way, the virus warning is something we also encountered in Clould4all in May 2014, when the version of GpiiUserListener110.exe we used in the second pilot phase triggered a virus warning in Avira.

**Pull request merged**
