### PR TITLE
GPII-2992: Stop narrator from staying active after acceptance tests

### PR DESCRIPTION
**Pull request by stegru**
Now waits for built-in AT to start.

### CODE REVIEW

**Comment by stegru** [comment]
ok to test

**Comment by stegru** [comment]
ok totest

**Comment by stegru** [comment]
ok to test

**Comment by stegru** [comment]
ok to test

```
05:58:03.927:  FATAL ERROR: Uncaught exception: Cannot find module 'kettle'
Error: Cannot find module 'kettle'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.fluid.require (\\vboxsvr\vagrant\node_modules\infusion\src\module\module.js:181:18)
    at Object.<anonymous> (\\vboxsvr\vagrant\gpii\node_modules\processReporter\test\all-tests.js:15:20)
```

**Comment by amb26** [comment]
This might be a real issue, due to the nutty way we load dependencies via universal. The top-level infusion may have diverged from universal's, leading to the following layout:
```
gpii-windows@0.3.0 E:\source\gits\gpii\node_modules\windows
+-- gpii-universal@0.3.0 (github:stegru/universal#77ca09a83a4358463041fda1c3fbe0ac45fd47d6)
| +-- gpii-pouchdb@1.0.12
| | +-- @the-t-in-rtf/express-pouchdb@4.0.0-20180523-1217
| | | `-- @the-t-in-rtf/pouchdb-all-dbs@1.0.2
| | |   `-- infusion@3.0.0-dev.20180222T160835Z.6e1311a  deduped
| | +-- gpii-express@1.0.13
| | | `-- infusion@3.0.0-dev.20180222T160835Z.6e1311a  deduped
| | `-- infusion@3.0.0-dev.20180222T160835Z.6e1311a  deduped
| +-- infusion@3.0.0-dev.20180222T160835Z.6e1311a
| `-- kettle@1.7.3
|   `-- infusion@3.0.0-dev.20180222T160835Z.6e1311a  deduped
`-- node-jqunit@1.1.8
  `-- infusion@3.0.0-dev.20171117T095227Z.67ff934
```
Replacing the include at the head of processReporter/test/all-tests.js with either
kettle = fluid.require("kettle", require)
or
kettle = fluid.require("%kettle")
should make the problem go away

**Comment by amb26** [comment]
Unusual, opaque failure:
```
doitclient.exe : doit: remote error: GetExitCodeProcess failed
    + CategoryInfo          : NotSpecified: (doit: remote er...eProcess failed:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
The following WinRM command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

do.ps1 -c 'node tests\AcceptanceTests.js builtIn'

Stdout from the command:
```

**Comment by stegru** [comment]
That's our new "node has crashed" error.

**Comment by amb26** [comment]
So will go away if https://github.com/GPII/windows/pull/177 is merged? But wasn't the point of #177 that we had a fault in the integration where failures would silently look like successes?

**Comment by stegru** [comment]
Yes it will go away with #177. That PR fixes the crash, but the successful fails have already been fixed on CI by @amatas with a new VM - hence this failure.

**Pull request merged**
