### PR TITLE
GPII-3853: Analysis related metrics improvements

### PR DESCRIPTION
**Pull request by stegru**
See https://github.com/GPII/universal/pull/790

### CODE REVIEW

**Comment by stegru** [comment]
ok to test

**Comment by stegru** [comment]
It looks like windows is out of sync with universal... https://github.com/GPII/windows/pull/261

```
    "message": "Cannot look up name gpii.windows.rm to a function with registered argumentMap - got defaults  ",
```

**Comment by stegru** [comment]
ok to test

```
03:04:32.363:  jq: FAIL: Module "gpii.tests.acceptance.windows.builtIn.config tests" Test name "Testing os_win using default matchmaker" - Message: Successful login message returned {"isError":true,"message":"Error occurred during login: Timed out waiting for the SPI call to complete (see GPII-2001)","ignoreUserErrors":false}
```

**Comment by stegru** [comment]
ok to test

```
04:12:12.665:  jq: FAIL: Module "gpii.tests.acceptance.windows.builtIn.config tests" Test name "Testing os_win using default matchmaker" - Message: Error making request to /user/os_win/login: socket hang up
```

**Comment by stegru** [comment]
fixed universal - ok to test

**Comment by javihernandez** [comment]
ok to test

**Comment by javihernandez** [comment]
> CI job failed: https://ci.gpii.net/job/windows-tests/1272/

```
Build was aborted
Aborted by unknown
Finished: ABORTED
```

ok to test

**Comment by stegru** [comment]
ok to test

**Comment by javihernandez** [comment]
> Aside these 2 minor comments, LGTM

Also, can you update it with current master?

**Comment by javihernandez** [comment]
> CI job failed: https://ci.gpii.net/job/windows-tests/1364/

```
04:49:17.224:  jq: FAIL: Module "Disable app bar" Test name "checking the window is in the correct position" - Message: Work area should have been restored - at sequence position 2 of 2
04:49:17.224:  jq: Expected: {
    "left": 0,
    "top": 0,
    "right": 1024,
    "bottom": 728
}
04:49:17.225:  jq: Actual: {
    "left": 0,
    "top": 0,
    "right": 800,
    "bottom": 560
}
```

Failure not related to the changes on this PR, ok to test

**Comment by stegru** [comment]
ok to test

**Comment by amb26** [comment]
Looks like a genuine unit test failure:
````
08:56:49.879:  No matching line (index=0):{
    "module": "metrics",
    "event": "app-launch",
    "data": {
        "exe": "%SystemRoot%\\System32\\VBoxTray.exe"
    }
}
08:56:49.879:  Remaining log lines:[
    {
        "module": "gpii",
        "event": "start",
        "level": "INFO",
        "installID": "OXXcEKGlSA",
        "version": "0.5.0",
        "timestamp": "2020-05-06T08:56:49.633-07:00",
        "sequence": 88780609632
    }
]
08:56:49.880:  jq: FAIL: Module "gpii.tests.metrics" Test name "Testing application metrics" - Message: Unable to find matching log entry 0
08:56:49.880:  jq: Source:     at pok (\\vboxsvr\vagrant\node_modules\infusion\tests\test-core\jqUnit\js\jqUnit.js:112:15)
    at Object.fail (\\vboxsvr\vagrant\node_modules\infusion\tests\test-core\jqUnit\js\jqUnit.js:129:13)
    at Array.<anonymous> (\\vboxsvr\vagrant\gpii\node_modules\windowsMetrics\test\WindowsMetricsTests.js:1150:16)
    at Object.that.complete (\\vboxsvr\vagrant\node_modules\infusion\src\framework\core\js\FluidPromises.js:70:25)
    at Object.that.reject (\\vboxsvr\vagrant\node_modules\infusion\src\framework\core\js\FluidPromises.js:61:22)
    at Interface.<anonymous> (\\vboxsvr\vagrant\gpii\node_modules\windowsMetrics\test\WindowsMetricsTests.js:1131:21)
    at Interface.emit (events.js:187:15)
    at Interface.close (readline.js:379:8)
    at ReadStream.onend (readline.js:157:10)
    at ReadStream.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1092:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
````

**Comment by amb26** [comment]
I can repeat this locally: 
````
04:57:36.861:  {"module":"gpii","event":"start","level":"INFO","installID":"OXXcEKGlSA","version":"0.5.0","timestamp":"2020-05-11T04:57:36.611-07:00","sequence":89198256611}
04:57:36.861:  No matching line (index=0):{
    "module": "metrics",
    "event": "app-launch",
    "data": {
        "exe": "%SystemRoot%\\System32\\VBoxTray.exe"
    }
}
04:57:36.861:  Remaining log lines:[
    {
        "module": "gpii",
        "event": "start",
        "level": "INFO",
        "installID": "OXXcEKGlSA",
        "version": "0.5.0",
        "timestamp": "2020-05-11T04:57:36.611-07:00",
        "sequence": 89198256611
    }
]
04:57:36.877:  jq: FAIL: Module "gpii.tests.metrics" Test name "Testing application metrics" - Message: Unable to find matching log entry 0
04:57:36.877:  jq: Source:     at pok (V:\node_modules\infusion\tests\test-core\jqUnit\js\jqUnit.js:112:15)
    at Object.fail (V:\node_modules\infusion\tests\test-core\jqUnit\js\jqUnit.js:129:13)
    at Array.<anonymous> (V:\gpii\node_modules\windowsMetrics\test\WindowsMetricsTests.js:1150:16)
    at Object.that.complete (V:\node_modules\infusion\src\framework\core\js\FluidPromises.js:70:25)
    at Object.that.reject (V:\node_modules\infusion\src\framework\core\js\FluidPromises.js:61:22)
    at Interface.<anonymous> (V:\gpii\node_modules\windowsMetrics\test\WindowsMetricsTests.js:1131:21)
    at Interface.emit (events.js:187:15)
    at Interface.close (readline.js:379:8)
    at ReadStream.onend (readline.js:157:10)
    at ReadStream.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1092:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
````
Please also update to gpii-universal 0.3.0-dev.20200506T153102Z.4f3572f

**Comment by stegru** [comment]
This is fixed by https://github.com/GPII/universal/pull/871

**Comment by stegru** [comment]
:facepalm:

**Pull request merged**
