### PR TITLE
GPII 2226: Screen scaling for Windows 10

### PR DESCRIPTION
**Pull request by stegru**
Added a "screen-dpi" setting to the display settings handler.

This uses API calls that are specific to Windows 10 (the ffi declarations wont even run on earlier versions), so there are separate files for each version being conditionally require()d.

(The initial research behind changing the DPI is in GPII-1716)

### CODE REVIEW

**Comment by stegru** [comment]
ok to test

**Comment by stegru** [comment]
ok to test

**Comment by amb26** [comment]
Unit tests fail for me - configuration is the current Windows vagrant box at screen res of 1920x1440:
```
08:22:03.363:  jq: Test concluded - Module "Windows Display Settings Handler Tests" Test name "Testing getScreenDpi ": 6/6 passed - PASS
08:22:03.551:  windows.display.getAvailableResolutions got available screen resolutions [
    {
        "dmPelsWidth": 640,
        "dmPelsHeight": 480
    },
    {
        "dmPelsWidth": 800,
        "dmPelsHeight": 600
    },
    {
        "dmPelsWidth": 1024,
        "dmPelsHeight": 768
    },
    {
        "dmPelsWidth": 1152,
        "dmPelsHeight": 864
    },
    {
        "dmPelsWidth": 1280,
        "dmPelsHeight": 960
    },
    {
        "dmPelsWidth": 1280,
        "dmPelsHeight": 1024
    },
    {
        "dmPelsWidth": 1400,
        "dmPelsHeight": 1050
    },
    {
        "dmPelsWidth": 1600,
        "dmPelsHeight": 1200
    },
    {
        "dmPelsWidth": 1920,
        "dmPelsHeight": 1440
    },
    {
        "dmPelsWidth": 2442,
        "dmPelsHeight": 1547
    }
]
08:22:04.792:  jq: FAIL: Module "Windows Display Settings Handler Tests" Test name "Testing setScreenDpi " - Message: setScreenDpi 325%
08:22:05.068:  jq: Expected: {
    "actual": 2.25,
    "configured": 3.25,
    "maximum": 2.25
}
08:22:05.224:  jq: Actual: {
    "configured": 3.5,
    "maximum": 2.25,
    "actual": 2.25
}
08:22:05.265:  jq: Source:     at Object.assertDeepEq (\\vboxsrv\vagrant\node_modules\infusion\tests\test-core\jqUnit\js\jqUnit.js:180:23)
    at Object.<anonymous> (\\vboxsrv\vagrant\gpii\node_modules\displaySettingsHandler\test\testDisplaySettingsHandler.js:213:16)
    at Object.run (\\vboxsrv\vagrant\node_modules\infusion\tests\lib\qunit\js\qunit.js:207:18)
    at \\vboxsrv\vagrant\node_modules\infusion\tests\lib\qunit\js\qunit.js:365:10
    at process (\\vboxsrv\vagrant\node_modules\infusion\tests\lib\qunit\js\qunit.js:1457:24)
    at Timeout._onTimeout (\\vboxsrv\vagrant\node_modules\infusion\tests\lib\qunit\js\qunit.js:483:5)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
08:22:06.144:  jq: Test concluded - Module "Windows Display Settings Handler Tests" Test name "Testing setScreenDpi ": 7/8 passed - FAIL
```

**Comment by stegru** [comment]
The values increase by .25, until 2.50 where they go up by .50. The test expected 3.25 (2.25 + 1)

**Pull request merged**
