### PR TITLE
Various Bugs for Windows Listeners - support NTAG and Provide installer

### PR DESCRIPTION
**Pull request by SteveALee**
* Builds with VS 2012
* Single EXE and no extra DLLs (removed libcurl.dll)
* USB listening now works
* No F11 hotkey to avoid clashes

### CODE REVIEW

**Comment by kaspermarkus** [comment]
Hey @SteveALee and @amb26, what's the status of this pull request? Should this stuff still go in, or has it been made obsolete from your listener work in the other repo, steve?

**Comment by SteveALee** [comment]
as far as i'm concerned it should go in. it's the latest listener for USB
devices. Hens spiked a listener to use the internal readers in some devices
like the LGS vaios.

We need to decide on a plan as currently they both use different APIs and
languages

discuss in architecture call today?

Steve Lee
OpenDirective http://opendirective.com

**Comment by sgithens** [comment]
This definately does not replace any work I'm doing. The listener I wrote is specifically for Windows 8 API's and is not supported by a huge amount of RFID hardware yet. (Including our APR122 readers)

**Comment by sgithens** [comment]
@SteveALee I do apologize for the lateness on this.  I will try to fast track.  However, I am unfortunately out next week, and I'm not sure if I'll get to it before I leave on Saturday... If no one else can do I will make it a super high priority the week I get back.  I do have VS and stuff installed so I should be able to test building it.

**Comment by SteveALee** [comment]
Thanks Steve. I'm also away next week for P4A.

Can we also move the Release over to GPII?

Thanks

Steve Lee

**Pull request merged**
