### PR TITLE
GPII-4016: App-zoom for explorer folder windows, notepad++, and wordpad.

### PR DESCRIPTION
**Pull request by stegru**
Added app-zoom support for explorer, Notepad++ and Wordpad.

### CODE REVIEW

**Comment by javihernandez** [comment]
LGTM. Extra points if you can update the README.md file of this module

**Comment by stegru** [comment]
I think the README is still up to date.

**Comment by stegru** [comment]
ok to test

```
04:15:33.970:  jq: FAIL: Module "gpii.tests.acceptance.windows.builtIn.config tests" Test name "Testing os_win using default matchmaker" - Message: Successful login message returned {"isError":true,"message":"Error occurred during login: Timed out waiting for the SPI call to complete (see GPII-2001)","ignoreUserErrors":false}
```

**Comment by javihernandez** [comment]
> I think the README is still up to date.

Right, I thought it contained information about how the screen zoom is performed on different applications, but I guess that the code is well documented for a reader to understand the particularities of every app.

**Pull request merged**
