### PR TITLE
GPII-4343: Saving the default theme if the current theme is unknown.

### PR DESCRIPTION
**Pull request by stegru**
Fixes the fault found in AJC3 where the high-contrast setting wasn't being restored.

To test: Unset `HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Themes@CurrentTheme`, it should still work.

### CODE REVIEW

**Comment by stegru** [comment]
ok to test

**Comment by javihernandez** [comment]
ok to test

**Comment by amb26** [comment]
ok to test

**Comment by amb26** [comment]
ok to test

**Comment by amb26** [comment]
Our well-known language names failure:
````
05:58:03.926:  languageNames failed
05:58:03.927:  jq: FAIL: Module "Windows Display Settings Handler Tests" Test name "Test getting language names" - Message: [object Object]
05:58:03.927:  jq: Source:     at pok (\\vboxsvr\vagrant\node_modules\infusion\tests\test-core\jqUnit\js\jqUnit.js:112:15)
    at Array.fail (\\vboxsvr\vagrant\node_modules\infusion\tests\test-core\jqUnit\js\jqUnit.js:129:13)
    at Object.that.complete (\\vboxsvr\vagrant\node_modules\infusion\src\framework\core\js\FluidPromises.js:70:25)
    at Object.that.reject (\\vboxsvr\vagrant\node_modules\infusion\src\framework\core\js\FluidPromises.js:61:22)
    at ChildProcess.<anonymous> (\\vboxsvr\vagrant\gpii\node_modules\gpii-localisation\src\language.js:242:21)
    at ChildProcess.emit (events.js:182:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
Build was aborted
Aborted by unknown
Finished: ABORTED
````

**Pull request merged**
