### PR TITLE
GPII-442: Detect Running Solutions (windows)

### PR DESCRIPTION
**Pull request by klown**
@kaspermarkus, @amb26  Here is the windows specific code for the Process Reporter.
Use with https://github.com/GPII/universal/pull/355

### CODE REVIEW

**Comment by gtirloni** [comment]
ok to test

**Comment by gtirloni** [comment]
ok to test

**Comment by amb26** [comment]
Hi, thanks @klown  - could you please regenerate this pull request so its clear which changes are in your branch vs those wich have been picked up from other branches? Thanks

**Comment by klown** [comment]
@amb26 For some reason, a previous merge of GPII master into the GPII-442 branch didn't take.  I've merged again, and it appears all of master is now merged in.  If that doesn't fix the problem, let me know, and I re-create the pull request.

> ... could you please regenerate this pull request so its clear which changes are in your branch vs those wich have been picked up from other branches?

**Comment by cindyli** [comment]
ok to test

**Comment by klown** [comment]
@gtirloni, The above failure has nothing to do with the code changes, but is a result of an inability of CI to fully create the VM.  From [the console log](https://ci.gpii.net/job/create-windows-vm/81/console):

> Timed out while waiting for the machine to boot.

Consequently, the unit tests fail because there is no VM to run them on.

**Comment by colinbdclark** [comment]
Hi @klown, it's @amatas who is responsible for build issues like the one you mention above, not @gtirloni. Alfredo, can you take a look whenever you get a chance?

**Comment by amatas** [comment]
ok to test

**Comment by amatas** [comment]
ok to test

**Comment by amatas** [comment]
@klown green bullet for this PR  :thumbsup: . Nothing to worry about at the server side, perhaps the VM became unresponsive because the full moon phase of was about to end.

**Comment by klown** [comment]
Thanks @amatas !
> @klown green bullet for this PR 👍 . Nothing to worry about at the server side, perhaps the VM became unresponsive because the full moon phase of was about to end.

So, the lesson is, "don't run until the full moon phase is done"?  I'll keep that in mind ;-)

**Comment by klown** [comment]
@amatas, I'm not sure why this failed.

Looking at [pipermail](http://lists.gpii.net/pipermail/ci/) shows only one test was run yesterday, but it's not this pull request.

Poking around Jenkins, I found the [correct console output](https://ci.gpii.net/job/windows-tests/151/console), which states that it bailed because it took more than 25 min to build the vm.  However, the related [vm build log](https://ci.gpii.net/job/create-windows-vm/146) says it was successful, and took 25 min total.

Any ideas?

**Comment by amatas** [comment]
ok to test

**Comment by amb26** [comment]
This is an odd failure - didn't we merge @stegru 's fix for this SPI issue?

```
13:51:52.916:  jq: FAIL: Module "SpiSettingsHandler Module" Test name "SpiSettingsHandler test - testMouse" - Message: Assert testMouse: MouseAcceleration
13:51:52.916:  jq: Expected: {
    "value": 2,
    "path": "pvParam.2"
}
13:51:52.916:  jq: Actual: {
    "value": 1,
    "path": "pvParam.2"
}
```

**Comment by amb26** [comment]
I guess you have conflicts - please merge up with master and see if the failures go away

**Comment by klown** [comment]
@amb,

> I guess you have conflicts - please merge up with master and see if the failures go away

It's strange:  I did [merge with master](https://github.com/GPII/windows/pull/82#commits-pushed-9314e16) and pushed but it stilled fails in CI.  I've since locally switched to an up-to-date master, and tested on a VM, and I'm seeing the same error.  I will continue to investigate.

> This is an odd failure - didn't we merge @stegru 's fix for this SPI issue?

Which JIRA?  Which pull request?/commit?  Browsing the [history](https://github.com/GPII/windows/commits/master) of the windows repository, the latest commit from @stegru is Mar  6: "[GPII-2315: Performed extra cleanup after AT closes](https://github.com/GPII/windows/commit/9b89b1567ba147bcc7674430b6ed0f81e8b057a1)".  When was his fix merged in?

**Comment by stegru** [comment]
This is it: https://github.com/stegru/windows/commit/6bfcbb7fd51efefb00107dbe2f7da4263a44ba6e

You might want to try @the-t-in-rtf's instructions: https://issues.gpii.net/browse/GPII-2495

**Comment by klown** [comment]
@stegru wrote:

> This is it: stegru/windows@6bfcbb7
> 
> You might want to try @the-t-in-rtf's instructions: https://issues.gpii.net/browse/GPII-2495

Yes, that fixes the Spi test failure that @amb26 documented above.  But that fix is not in master, and CI will continue to fail.

Thanks, @stegru!

**Comment by klown** [comment]
ok to test

**Comment by klown** [comment]
ok to test

**Comment by gtirloni** [comment]
ok to test

**Comment by amb26** [comment]
Hi @klown - I get a lot of test failures like the following in our standard vagrant Windows 10 box pointing this branch at current universal:
```
06:12:54.622:  jq: FAIL: Module "Processes Bridge for Windows module" Test name "Test getProceses('node')/findProcessByPid() with the nodejs process itself" - Message: Listing all processes
06:12:54.622:  jq: Expected: 0
06:12:54.622:  jq: Actual: 0
06:12:54.622:  jq: Source:     at Object.assertNotEquals (\\vboxsrv\vagrant\node_modules\infusion\tests\test-core\jqUnit\js\jqUnit.js:141:19)
    at Object.<anonymous> (\\vboxsrv\vagrant\gpii\node_modules\processReporter\test\processesBridge_tests.js:43:16)
    at Object.run (\\vboxsrv\vagrant\node_modules\infusion\tests\lib\qunit\js\qunit.js:207:18)
    at \\vboxsrv\vagrant\node_modules\infusion\tests\lib\qunit\js\qunit.js:365:10
    at process (\\vboxsrv\vagrant\node_modules\infusion\tests\lib\qunit\js\qunit.js:1457:24)
    at Timeout._onTimeout (\\vboxsrv\vagrant\node_modules\infusion\tests\lib\qunit\js\qunit.js:483:5)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
06:12:54.633:  jq: FAIL: Module "Processes Bridge for Windows module" Test name "Test getProceses('node')/findProcessByPid() with the nodejs process itself" - Message: Searching for 'node' process
06:12:54.633:  jq: Source:     at pok (\\vboxsrv\vagrant\node_modules\infusion\tests\test-core\jqUnit\js\jqUnit.js:112:15)
    at Object.assertNotNull (\\vboxsrv\vagrant\node_modules\infusion\tests\test-core\jqUnit\js\jqUnit.js:173:13)
    at Object.<anonymous> (\\vboxsrv\vagrant\gpii\node_modules\processReporter\test\processesBridge_tests.js:51:16)
    at Object.run (\\vboxsrv\vagrant\node_modules\infusion\tests\lib\qunit\js\qunit.js:207:18)
    at \\vboxsrv\vagrant\node_modules\infusion\tests\lib\qunit\js\qunit.js:365:10
    at process (\\vboxsrv\vagrant\node_modules\infusion\tests\lib\qunit\js\qunit.js:1457:24)
    at Timeout._onTimeout (\\vboxsrv\vagrant\node_modules\infusion\tests\lib\qunit\js\qunit.js:483:5)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
06:12:54.633:  jq: Test concluded - Module "Processes Bridge for Windows module" Test name "Test getProceses('node')/findProcessByPid() with the nodejs process itself": 0/2 passed - FAIL
06:12:54.633:  jq: FAIL: Module "Processes Bridge for Windows module" Test name "Test getProceses()/findProcessByPid() with the nodejs process itself" - Message: Listing all processes
06:12:54.633:  jq: Expected: 0
06:12:54.633:  jq: Actual: 0
06:12:54.633:  jq: Source:     at Object.assertNotEquals (\\vboxsrv\vagrant\node_modules\infusion\tests\test-core\jqUnit\js\jqUnit.js:141:19)
    at Object.<anonymous> (\\vboxsrv\vagrant\gpii\node_modules\processReporter\test\processesBridge_tests.js:59:16)
    at Object.run (\\vboxsrv\vagrant\node_modules\infusion\tests\lib\qunit\js\qunit.js:207:18)
    at \\vboxsrv\vagrant\node_modules\infusion\tests\lib\qunit\js\qunit.js:365:10
    at process (\\vboxsrv\vagrant\node_modules\infusion\tests\lib\qunit\js\qunit.js:1457:24)
    at Timeout._onTimeout (\\vboxsrv\vagrant\node_modules\infusion\tests\lib\qunit\js\qunit.js:483:5)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
06:12:54.633:  jq: FAIL: Module "Processes Bridge for Windows module" Test name "Test getProceses()/findProcessByPid() with the nodejs process itself" - Message: Searching for 'node' process
06:12:54.633:  jq: Source:     at pok (\\vboxsrv\vagrant\node_modules\infusion\tests\test-core\jqUnit\js\jqUnit.js:112:15)
    at Object.assertNotNull (\\vboxsrv\vagrant\node_modules\infusion\tests\test-core\jqUnit\js\jqUnit.js:173:13)
    at Object.<anonymous> (\\vboxsrv\vagrant\gpii\node_modules\processReporter\test\processesBridge_tests.js:67:16)
    at Object.run (\\vboxsrv\vagrant\node_modules\infusion\tests\lib\qunit\js\qunit.js:207:18)
    at \\vboxsrv\vagrant\node_modules\infusion\tests\lib\qunit\js\qunit.js:365:10
    at process (\\vboxsrv\vagrant\node_modules\infusion\tests\lib\qunit\js\qunit.js:1457:24)
    at Timeout._onTimeout (\\vboxsrv\vagrant\node_modules\infusion\tests\lib\qunit\js\qunit.js:483:5)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
06:12:54.633:  jq: Test concluded - Module "Processes Bridge for Windows module" Test name "Test getProceses()/findProcessByPid() with the nodejs process itself": 0/2 passed - FAIL
```

Could you update the pull to point to universal master and see what CI says? Cheers

**Comment by amb26** [comment]
Merged into master at revision 89c7a6410c98bef557a9de46a77f2b989e69ac92 - thanks for the patient, long-term work!

**Pull request closed without merging**
