### PR TITLE
GPII-1716: Fontsize support for Windows 10

### PR DESCRIPTION
**Pull request by stegru**
Only implemented for Windows 10 - it works on lower versions in the sense that it does nothing (it doesn't crash).

"gert" is a good person to use, and it requires a resolution of at least 1024x768.

### CODE REVIEW

**Comment by javihernandez** [comment]
ok to test

**Comment by gtirloni** [comment]
ok to test

**Comment by gtirloni** [comment]
ok to test

**Comment by stegru** [comment]
The acceptance tests for this are going to fail, because it relies on https://github.com/GPII/universal/pull/493.

https://github.com/GPII/windows/pull/102/commits/65536ad7beefe5e422df61dc1bc41e3aa86b9704 shows it passing, as I (temporarily) removed the DPI setting block from the settings handler output.

**Comment by stegru** [comment]
Closed for https://issues.gpii.net/browse/GPII-2226

**Pull request closed without merging**
