### PR TITLE
GPII-1993 : Port of infrastructure scripts from BAT to PowerShell.

### PR DESCRIPTION
**Pull request by gloob**
Created a new Powershell module "Provisioning.psm1" for containing all the needed function and aliases for building GPII in any Windows version. Create new Powershell script "Build.ps1" mimicking the behaviour of build.bat.

### CODE REVIEW

**Comment by gloob** [comment]
This PR is ready for review.

I recommend to first merge PR #92 (changes incorporated in this PR) and later PR #76. After inclusion of this two PRs I will update this PR with accepted changes from #76.

**Comment by gtirloni** [comment]
@gloob it looks like those PRs got merged, could you rebase?

Also, it might be good to change the version to 6.9.0 which will be the first LTS release for the 6.x branch (to be released this Tuesday).

I've tested this PR with node 6.8.1 and the latest Windows 10 box that Alfredo created, and it passed all tests.

**Comment by gloob** [comment]
Ready for review and merge. Included previous PRs #97 #88 and #76.

**Comment by javihernandez** [comment]
I've just finished to test this and in general it looks very good to me. I really like the flexibility and all the benefits we obtain from moving our provisioning stuff into powershell scripts. 
@amatas, @avtar or @gtirloni, since these changes are related to provisioning, I'd appreciate any feedback/comment from you before merging it (even if it's just a :+1:)

**Comment by amatas** [comment]
I've spinned up a VM with this PR and it looks good to me. Also I like that you'll get a fresh installer at C:\installer\output when the provision of the VM ends.

**Comment by javihernandez** [comment]
This is IN! (https://github.com/GPII/windows/commit/3eb9e8c4bda54bc583af7309998ab202370bde23)
:beers: :beers: :beers:

**Comment by colinbdclark** [comment]
Congrats, @gloob! Nice work!

**Pull request merged**
