### PR TITLE
GPII-3139: Onboard Windows 10 "Ease of access" -> "Additional Keyboard features"

### PR DESCRIPTION
**Pull request by JavierJF**

### CODE REVIEW

**Comment by stegru** [comment]
It would be nice to have some simple instructions on how to test and what to expect.

ok to test

**Comment by stegru** [comment]
ok to test

```
Vagrant can't use the requested machine because it is locked! This
means that another Vagrant process is currently reading or modifying
the machine. Please wait for that Vagrant process to end and try
again. Details about the machine are shown below:

Name: default
Provider: virtualbox
Build step 'Execute shell' marked build as failure
Finished: FAILURE
```

**Comment by JavierJF** [comment]
ok to test

**Comment by JavierJF** [comment]
ok to test

**Comment by JavierJF** [comment]
ok to test

**Comment by JavierJF** [comment]
ok to test

**Comment by JavierJF** [comment]
ok to test

**Comment by stegru** [comment]
ok to test

**Comment by stegru** [comment]
Just needs master update + conflicts resolving

ok to test

**Comment by JavierJF** [comment]
Ok to test

**Comment by JavierJF** [comment]
Ok to test

**Comment by JavierJF** [comment]
Pushed Windows before updating universal branch, testing again.

**Comment by JavierJF** [comment]
Ok to test

**Comment by JavierJF** [comment]
Build was aborted, retrying again.

```
Build was aborted
Aborted by unknown
Finished: ABORTED
```
https://ci.gpii.net/job/windows-unit-tests/872/consoleFull

**Comment by JavierJF** [comment]
Ok to test

**Comment by JavierJF** [comment]
Fixed the source of the error in universal. Testing again.

**Comment by JavierJF** [comment]
Ok to test

**Pull request merged**
