### PR TITLE
GPII-4382: Updated to use universal branch to test work in progress.

### PR DESCRIPTION
**Pull request by the-t-in-rtf**
This merge is only to demonstrate the viability of another pull as an upstream dependency.  It should not be merged.

See [the associated universal pull for details](https://github.com/GPII/universal/pull/852) for details.

cc: @amb26

### CODE REVIEW

**Comment by the-t-in-rtf** [comment]
OK, leaving the `Scaling` setting in caused problems, I commented that out for now.  Ok to test.

**Comment by the-t-in-rtf** [comment]
So, I am still working on getting the acceptance tests working.  I worked through a few variations, settings that the SPI handler couldn't work with, an incorrect schema for the display settings.  At this point I'm really stuck, the acceptance tests crash the shell itself without any useful diagnostic information.  I would appreciate any insight others on the team can provide.

cc: @kaspermarkus @amb26 @stegru

**Comment by the-t-in-rtf** [comment]
I believe we're finally ok to test again.

**Comment by amb26** [comment]
ok to test

**Comment by amb26** [comment]
ok to test

**Comment by amb26** [comment]
Failure was in the WindowsArrangement setting of the SpiSettingsHandler:
````
Expected:
                "settings": {
                    "WindowsArrangement": {
                        "value": 1,
                        "path": {
                            "get": "pvParam",
                            "set": "uiParam"
                        }
                    }
                }
            },
Actual:
            {
                "settings": {
                    "WindowsArrangement": {
                        "value": 0,
                        "path": {
                            "get": "pvParam",
                            "set": "uiParam"
                        }
                    }
                }
            },
````
Given this works sometimes I'm taking it as nothing to do with your schema/default value work and written it up as https://issues.gpii.net/browse/GPII-4405

However, I also note that virtually every time when run manually in the VM, the acceptance tests now leave the magnifier and the on-screen keyboard open, just like in the good old days.

**Pull request merged**
