### PR TITLE
GPII-3744: Added provisioning script to install and setup CouchDB

### PR DESCRIPTION
**Pull request by javihernandez**
See https://issues.gpii.net/browse/GPII-3744

### CODE REVIEW

**Comment by javihernandez** [comment]
Bingo: 

```
==> default: Running provisioner: shell...
    default: Running: provisioning/CouchDB.ps1 as c:\tmp\vagrant-shell.ps1
    default: VERBOSE: Exporting function 'Invoke-Command'.
    default: VERBOSE: Exporting function 'Get-MSBuild'.
    default: VERBOSE: Exporting function 'Invoke-Environment'.
    default: VERBOSE: Exporting function 'Add-Path'.
    default: Downloading CouchDB from http://archive.apache.org/dist/couchdb/binary/win/2.3.0/couchdb-2.3.0.msi
    default: Installing CouchDB ...
    default: VERBOSE: Execute-Command Started ( : msiexec.exe /i C:\vagrant\provisioning\couchdb-2.3.0.msi /passive).
    default: VERBOSE: 'msiexec.exe' exited with 0
    default: Configuring CouchDB ...
    default: Changing default listening port to 25984 ...
    default: Restarting CouchDB ...
    default: CouchDB is now installed and configured
```

**Comment by amb26** [comment]
ok to test

**Comment by javihernandez** [comment]
> CI job failed: https://ci.gpii.net/job/windows-tests/885/

```
 default: Configuring CouchDB ...
    default: ERROR: CouchDB couldn't be installed. Error was Unable to connect to the remote server
The following WinRM command responded with a non-zero exit status.
```

Hmm, looks like we attempted to set up couchdb too early after being installed.

ok to test

**Comment by javihernandez** [comment]
ok to test

**Comment by javihernandez** [comment]
Same thing again: 
```
default: Configuring CouchDB ...
    default: ERROR: CouchDB couldn't be installed. Error was Unable to connect to the remote server
The following WinRM command responded with a non-zero exit status.
``` 
ok to test

**Comment by amb26** [comment]
Hi @javihernandez - try binding this to universal release 0.3.0-dev.20190227T223912Z.acb045a3 which incorporates @cindyli  's fixes for acceptance tests runs on Windows - cheers!

**Pull request merged**
