### PR TITLE
GPII-2402: Replaced "login" and "logout" with "proximityTrigger"

### PR DESCRIPTION
**Pull request by stegru**
The fixes to work with https://github.com/GPII/universal/pull/513 which take the "logged in/out" state out of the RFID listener.

However, "logout" is still sent when the listener is closed (or the reader has gone).

### CODE REVIEW

**Comment by kaspermarkus** [comment]
hi @amb26 - I think this one is a priority now that GPII-2402 from universal is in... I unfortunately do not know c++ well enough to review this (though looking through the code, all changes seems quite sensible :) )

**Comment by kaspermarkus** [comment]
@stegru The universal portion of this is now merged, so the package.json should reference the latest universal (https://github.com/GPII/universal/commit/3159f2013d8752c403f6cee47b072c95a057e4a4)

**Comment by stegru** [comment]
Done, @kaspermarkus.
I hope you didn't change the endpoint names - I'm unable to test this because the listener doesn't work with my reader.

**Comment by javihernandez** [comment]
@stegru can you update this pull request with current master?

**Comment by stegru** [comment]
@javihernandez done, but I left it referring to kasper's universal branch

**Comment by stegru** [comment]
Well, that failed on something completely unrelated - you might want to ok to test it again

**Comment by javihernandez** [comment]
> @javihernandez done, but I left it referring to kasper's universal branch

I don't quite understand. Kasper's pull request was merged last week, so it is now in universal/master. During the weekend, windows/master was updated to use the last version of universal, so you should just use the same reference to universal used in windows/master. Then the tests will pass ;)

**Comment by stegru** [comment]
Oh!!

**Comment by javihernandez** [comment]
ok to test

**Comment by stegru** [comment]
As discussed:
- proximityRemoved is a potential future improvement.
- "logout" is now completely removed.

**Pull request merged**
