### PR TITLE
Fix processes bridge to run the same in PowerShell as in Command Prompt

### PR DESCRIPTION
**Pull request by klown**
@javihernandez, here's a pull request to fix the unit test in gpii-app. 

The problem: when run under PowerShell, the C# code returns slightly different information compared to when run under the older command prompt.  CI for the windows repo uses the command prompt for the unit tests (and they all pass).  Gpii-app, however, is launched via a PowerShell script, and the difference causes that one unit test to fail.  I've normalized the output of the C# code such that it should no longer matter.

I hope this does the trick.

### CODE REVIEW

**Comment by klown** [comment]
ok to test

**Comment by gtirloni** [comment]
ok to test

**Comment by klown** [comment]
ok to test

**Comment by klown** [comment]
@javihernandez The changes above fix one of the test failures.  But, there is still one failure, and it's tricky to diagnose.  It's not a test failure, but something to do when no argument is passed to `getProcessList()`.  It works fine in the windows branch.  Still diagnosing in gpii-app.

**Comment by klown** [comment]
Update @javihernandez: I have figured out the other bug, but haven't finished the solution.  I'll take it up again in the morning.

**Comment by klown** [comment]
ok to test

**Comment by javihernandez** [comment]
ok to test

**Comment by klown** [comment]
ok to test

**Comment by klown** [comment]
ok to test

**Comment by javihernandez** [comment]
This won't pass until we update the vagrant box OR get [this](https://github.com/GPII/windows/pull/148) merged into master

**Comment by javihernandez** [comment]
@klown can you update this pull request with master?

**Pull request merged**
