### PR TITLE
GPII-3648: Onboard Windows 10 "Magnifier" -> "Additional features"

### PR DESCRIPTION
**Pull request by JavierJF**
**Warning: Do not merge**

This pull request is simply for making seeing acceptance tests output in CI.

### CODE REVIEW

**Comment by JavierJF** [comment]
Ok to test

**Comment by JavierJF** [comment]
Unrelated DPI error, probably related to VM. Testing again.

image

**Comment by JavierJF** [comment]
Ok to test

**Comment by JavierJF** [comment]
Ok to test

**Comment by JavierJF** [comment]
Looks like a unrelated error in the processHandling unit tests:

image

Testing again.

**Comment by JavierJF** [comment]
Ok to test

**Comment by amb26** [comment]
Closed since just dep update - will be incorporated on next update since https://github.com/GPII/universal/pull/731 is merged

**Pull request closed without merging**
