### PR TITLE
GPII-4428: Restoring icon spacing when restarting explorer

### PR DESCRIPTION
**Pull request by amb26**
CI run for #312

### CODE REVIEW

**Comment by amb26** [comment]
Hi @stegru - I used to get this just locally but now it has turned up in CI too - could you investigate - cheers!
````
07:37:22.674:  jq: FAIL: Module "gpii.tests.windows.processHandling" Test name "Testing startProcess" - Message: startProcess (second instance test) should return a zero PID
07:37:22.674:  jq: Expected: 0
07:37:22.674:  jq: Actual: 1652
07:37:22.675:  jq: Source:     at Object.assertEquals (\\vboxsvr\vagrant\node_modules\infusion\tests\test-core\jqUnit\js\jqUnit.js:137:19)
    at runTest (\\vboxsvr\vagrant\gpii\node_modules\processHandling\test\testProcessHandling.js:473:20)
    at Array.<anonymous> (\\vboxsvr\vagrant\gpii\node_modules\processHandling\test\testProcessHandling.js:496:13)
    at Object.that.complete (\\vboxsvr\vagrant\node_modules\infusion\src\framework\core\js\FluidPromises.js:70:25)
    at Object.that.resolve (\\vboxsvr\vagrant\node_modules\infusion\src\framework\core\js\FluidPromises.js:52:22)
    at Timeout.checkCondition [as _onTimeout] (\\vboxsvr\vagrant\gpii\node_modules\windowsUtilities\WindowsUtilities.js:2047:21)
    at ontimeout (timers.js:425:11)
    at tryOnTimeout (timers.js:289:5)
    at listOnTimeout (timers.js:252:5)
    at Timer.processTimers (timers.js:212:10)
````

**Comment by amb26** [comment]
ok to test

**Comment by amb26** [comment]
ok to test

**Comment by amb26** [comment]
ok to test

**Comment by amb26** [comment]
ok to test

**Comment by stegru** [comment]
It turns out that it should have been waiting for the initial processes window to appear, rather than the actual process to start. (the "activate existing instance instead of starting" feature expects a window to activate).

https://github.com/GPII/windows/pull/312/commits/4ef4cecd84e44e984ff59ae11db3c9e27e383ca2

**Comment by amb26** [comment]
ok to test

**Comment by amb26** [comment]
SPI timeout again - @stegru, is there really nothing we can do about this?
````
08:25:40.030:  jq: FAIL: Module "gpii.tests.acceptance.windows.builtIn.config tests" Test name "Testing os_win using default matchmaker" - Message: Successful login message returned {"isError":true,"message":"Error occurred during login: Timed out waiting for the SPI call to complete (see GPII-2001)","ignoreUserErrors":false}
08:25:40.031:  jq: Expected: -1
08:25:40.031:  jq: Actual: -1
08:25:40.031:  jq: Source:     at Object.assertNotEquals (\\vboxsvr\vagrant\node_modules\infusion\tests\test-core\jqUnit\js\jqUnit.js:141:19)
````

**Pull request merged**
