### PR TITLE
GPII-4403, GPII-4401: Fixes to the gpiiKey generation

### PR DESCRIPTION
**Pull request by stegru**
gpiiKeys are now generated using:
* Lower cased usernames (GPII-4401)
* The secret from the site credentials (GPII-4403)

### CODE REVIEW

**Comment by javihernandez** [comment]
ok to test

**Comment by stegru** [comment]
ok to test
```
06:30:00.516:  jq: FAIL: Module "gpii.tests.acceptance.windows.builtIn.config tests" Test name "Testing os_win using default matchmaker" - Message: Successful login message returned {"isError":true,"message":"Error occurred during login: Timed out waiting for the SPI call to complete (see GPII-2001)","ignoreUserErrors":false}
```

**Comment by stegru** [comment]
ok to test

```
08:32:40.135:  jq: FAIL: Module "gpii.tests.acceptance.windows.builtIn.config tests" Test name "Testing os_common - magnifier running on startup" - Message: Checking that settings are properly reset - at sequence position 24 of 30
08:32:40.136:  jq: Expected: {
    "gpii.windows.spiSettingsHandler": {
        "com.microsoft.windows.mouseTrailing": [
```

**Comment by amb26** [comment]
Cheers @stegru - please update for conflicts

**Pull request merged**
