### PR TITLE
GPII-3131: Onboard 'Audio Description' and 'Notification duration' from Windows 10 

### PR DESCRIPTION
**Pull request by JavierJF**

### CODE REVIEW

**Comment by stegru** [comment]
ok to test

**Comment by JavierJF** [comment]
Ok to test

**Comment by JavierJF** [comment]
ok to test

**Comment by stegru** [comment]
This only needs to have master merged, without the conflict.

**Comment by JavierJF** [comment]
Ok to test.

**Comment by JavierJF** [comment]
ok to test

**Comment by JavierJF** [comment]
ok to test

**Comment by stegru** [comment]
ok to test

**Comment by amatas** [comment]
ok to test

**Comment by stegru** [comment]
Depends on https://github.com/GPII/universal/pull/624

**Comment by JavierJF** [comment]
Ok to test

**Pull request merged**
