### PR TITLE
GPII-3864: Onboard Windows 10 volume

### PR DESCRIPTION
**Pull request by JavierJF**

### CODE REVIEW

**Comment by amb26** [comment]
Could you strip out the binary VS files which I assume are not necessary to get the project to build? I assume at the least that the 35MB "Browse.VC.db" is not necessary

**Comment by JavierJF** [comment]
@amb26 In fact I just check and I could suppress the whole folder without any issues, so, it should look cleaner now.

**Comment by amb26** [comment]
Hi there @JavierJF - very nearly ready to merge this, I wonder if you could just tidy up by adding a .gitignore that will suppress the contents of 
````
        gpii/node_modules/nativeSettingsHandler/nativeSolutions/VolumeControl/Release/
        gpii/node_modules/nativeSettingsHandler/nativeSolutions/VolumeControl/VolumeControl/Release/
````
which are currently marked as dirty?
Might also be helpful to fix the project settings so that only one such directory is created - thanks!

**Comment by JavierJF** [comment]
Hi@amb26, sorry for the delay. I have added the directories to .gitignore, the two directories are because one is for the project, and the other for the visual studio solution (.sln) itself. I can try to workaround this tomorrow if it's needed, to see if I can get just one build directory.

**Comment by JavierJF** [comment]
Failed created VM, testing again:
image

**Comment by JavierJF** [comment]
Ok to test

**Pull request merged**
