### PR TITLE
GPII-4367: Re-added the frameworkPathOverride to NpmInstall.ps1

### PR DESCRIPTION
**Pull request by javihernandez**
And updated according to the currently installed version of the .Net
framework in the windows vagrant box (2020.02.11)

### CODE REVIEW

**Comment by javihernandez** [comment]
@stegru @JavierJF does this make sense to you?

**Comment by stegru** [comment]
Yes :point_down: 

image

**Comment by amb26** [comment]
Doesn't work for the app, any clues why? https://github.com/GPII/gpii-app/pull/182#issuecomment-588971581

**Comment by stegru** [comment]
This fix did appear to work.

From the [gpii-app build](https://ci.gpii.net/job/create-gpii-app-vm/979/consoleText): 

```
 default: C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe SettingsHelper.sln /p:Configuration=Release /p:Platform="Any 
    default: CPU" /p:FrameworkPathOverride="C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.1").
    default: Microsoft (R) Build Engine version 4.8.3752.0
    default: [Microsoft .NET Framework, version 4.0.30319.42000]
    default: Copyright (C) Microsoft Corporation. All rights reserved.
    default: Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
    default: Build started 2/20/2020 2:31:42 AM.
    default: Project "V:\node_modules\gpii-windows\settingsHelper\SettingsHelper.sln" on node 1 (default targets).
    default: ValidateSolutionConfiguration:
    default:   Building solution configuration "Release|Any CPU".
    default: Project "V:\node_modules\gpii-windows\settingsHelper\SettingsHelper.sln" (1) is building "V:\node_modules\gpii-windows\settingsHelper\SettingsHelper\SettingsHelper.csproj" (2) on node 1 (default targets).
    default: Project file contains ToolsVersion="15.0". This toolset may be unknown or missing, in which case you may be able to resolve this by installing the appropriate version of MSBuild, or the build may have been forced to a particular ToolsVersion for policy reasons. Treating the project as if it had ToolsVersion="4.0". For more information, please see http://go.microsoft.com/fwlink/?LinkId=291333.
    default: PrepareForBuild:
    default:   Creating directory "..\..\bin\".
    default:   Creating directory "obj\Release\".
    default: CoreCompile:
    default:   C:\Windows\Microsoft.NET\Framework\v4.0.30319\Csc.exe /noconfig /nowarn:1701,1702 /nostdlib+ /platform:AnyCPU /errorreport:prompt /warn:4 /define:TRACE /highentropyva+ /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.1\Microsoft.CSharp.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.1\mscorlib.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.1\System.Core.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.1\System.Data.DataSetExtensions.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.1\System.Data.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.1\System.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.1\System.Net.Http.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.1\System.Runtime.Serialization.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.1\System.Xml.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.1\System.Xml.Linq.dll" /debug- /filealign:512 /optimize+ /out:obj\Release\SettingsHelper.exe /subsystemversion:6.00 /target:exe /utf8output /win32manifest:app.manifest ISettingItem.cs SettingsHelper.cs Properties\AssemblyInfo.cs SettingHandler.cs SettingItem.cs "C:\Users\vagrant\AppData\Local\Temp\.NETFramework,Version=v4.5.1.AssemblyAttributes.cs"
    default: CopyFilesToOutputDirectory:
    default:   Copying file from "obj\Release\SettingsHelper.exe" to "..\..\bin\SettingsHelper.exe".
    default:   SettingsHelper -> V:\node_modules\gpii-windows\bin\SettingsHelper.exe
    default: Done Building Project "V:\node_modules\gpii-windows\settingsHelper\SettingsHelper\SettingsHelper.csproj" (default targets).
    default: Done Building Project "V:\node_modules\gpii-windows\settingsHelper\SettingsHelper.sln" (default targets).
    default: Build succeeded.
    default:     0 Warning(s)
    default:     0 Error(s)
    default: Time Elapsed 00:00:02.95
```

**Pull request merged**
