### PR TITLE
checking master sanity

### PR DESCRIPTION
**Pull request by stegru**

### CODE REVIEW

**Comment by stegru** [comment]
random error in the provisioning

```
default: prebuild verb check python checking for Python executable "python2" in the PATH
    default: prebuild verb `which` failed Error: not found: python2
```

**Comment by stegru** [comment]
ok to test

**Comment by stegru** [comment]
still not finding python.

works locally... might be be a temporary external issue

ok to test

**Comment by javihernandez** [comment]
weird, the log claims that python is indeed installed and added to the system path

```
default: Progress: Downloading python2 2.7.17... 100%
    default: python2 v2.7.17 [Approved]
    default: python2 package files install completed. Performing other installation steps.
    default: Installing 64-bit python2...
    default: python2 has been installed.
    default: Installed to 'C:\Python27'
    default: Adding C:\Python27 to PATH if needed
    default:   python2 may be able to be automatically uninstalled.
    default: Environment Vars (like PATH) have changed. Close/reopen your shell to
    default:  see the changes (or in powershell/cmd.exe just type `refreshenv`).
    default:  The install of python2 was successful.
    default:   Software installed as 'msi', install location is likely default.
    default: Chocolatey installed 1/1 packages. 
    default:  See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
    default: VERBOSE: 'C:\ProgramData\chocolatey\bin\choco.exe' exited with 0
    default: VERBOSE: Add-Path Local C:\tools\python2 -> C:\Users\vagrant\AppData\Roaming\npm;C:\Program Files 
    default: (x86)\nodejs\;C:\Program Files (x86)\Common 
    default: Files\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShel
    default: l\v1.0\;C:\Windows\System32\OpenSSH\;C:\ProgramData\chocolatey\bin;C:\Program Files\Git\cmd;C:\Program Files 
    default: (x86)\Windows Kits\8.1\Windows Performance 
    default: Toolkit\;C:\Users\vagrant\AppData\Local\Microsoft\WindowsApps;C:\tools\python2
    default: VERBOSE: Add-Path System C:\tools\python2 in the registry: C:\Python27\;C:\Python27\Scripts;C:\Program Files 
    default: (x86)\Common 
    default: Files\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShel
    default: l\v1.0\;C:\Windows\System32\OpenSSH\;C:\ProgramData\chocolatey\bin;C:\Program Files\Git\cmd;C:\Program Files 
    default: (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files (x86)\nodejs\;C:\tools\python2.
    default: C:\Users\vagrant\AppData\Roaming\npm;C:\Program Files (x86)\nodejs\;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\ProgramData\chocolatey\bin;C:\Program Files\Git\cmd;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Users\vagrant\AppData\Local\Microsoft\WindowsApps;C:\tools\python2
    default: Refreshing environment variables from registry for cmd.exe. Please wait...Finished..
```

ok to test

**Comment by stegru** [comment]
The python path was a red herring. I couldn't get it to fail locally because I did not delete `package-lock.json`.

The real error:
```
    default: v:\node_modules\leveldown\node_modules\nan\nan_maybe_43_inl.h(88): error C2039: 'ForceSet': is not a member of 'v8::Object' (compiling source file ..\src\batch.cc) [V:\node_modules\leveldown\build\leveldown.vcxproj]
    default:   v:\node_modules\leveldown\10.11.0\include\node\v8.h(3239): note: see declaration of 'v8::Object' (compiling source file ..\src\batch.cc)
```

It looks like there was a problem in the universal release that I referenced (let's see if CI agrees)

**Comment by amb26** [comment]
leveldown?! That was deleted from universal months ago ...

**Comment by stegru** [comment]
Ah crap, I just realised I used an old universal release.

https://www.npmjs.com/package/gpii-universal:

image

**Comment by stegru** [comment]
Test is completing before the child process has completely terminated

```
04:26:14.144:  jq: FAIL: Module "gpii.tests.windows.processHandling" Test name "Testing closeProcessByName (window-less process)" - Message: Teardown failed on Testing closeProcessByName (window-less process): EPERM: operation not permitted, unlink 'C:/Users/vagrant/AppData/Local/Temp/gpii-process-handling-test.exe'
04:26:14.145:  jq: Source:     at Object.unlinkSync (fs.js:930:3)
```

ok to test

**Comment by stegru** [comment]
no longer required

**Pull request closed without merging**
