### PR TITLE
GPII-1851: Remove the Inno-based User Listener installer code

### PR DESCRIPTION
**Pull request by minogian**

### CODE REVIEW

**Comment by javihernandez** [comment]
ok to test

**Comment by minogian** [comment]
Rebased and resolved conflicts found after https://github.com/GPII/windows/pull/93 was merged

**Comment by gloob** [comment]
Perfect @minogian. This is ready for review.

**Comment by javihernandez** [comment]
@sgithens @stegru can you take care of reviewing this?

**Pull request merged**
