### PR TITLE
GPII-2844: Stop and restart Windows explorer

### PR DESCRIPTION
**Pull request by stegru**
Provides the functionality to cleanly stop and restart windows explorer (the tasktray).

This contains https://github.com/GPII/windows/pull/169, which in turn depends on https://github.com/GPII/universal/pull/600

### CODE REVIEW

**Comment by stegru** [comment]
hi @JavierJF

**Comment by stegru** [comment]
ok to test

**Comment by stegru** [comment]
```
==> default: Destroying VM and associated drives...
/opt/vagrant/embedded/gems/gems/httpclient-2.8.3/lib/httpclient/session.rb:623:in `rescue in create_socket': Connection refused - Connection refused - connect(2) for "127.0.0.1" port 5985 (127.0.0.1:5985) (Errno::ECONNREFUSED)
	from /opt/vagrant/embedded/gems/gems/httpclient-2.8.3/lib/httpclient/session.rb:607:in `create_socket'
```

ok to test

**Comment by JavierJF** [comment]
This pulls looks good to me, I'm going to use it in pull [GPII-2521](https://github.com/GPII/windows/pull/152) to achieve explorer restart.

**Pull request closed without merging**
