### PR TITLE
NOJIRA: Testing Windows sanity

### PR DESCRIPTION
**Pull request by amb26**

### CODE REVIEW

**Comment by amb26** [comment]
ok to test

**Comment by amb26** [comment]
VM locked: Vagrant can't use the requested machine because it is locked! This
means that another Vagrant process is currently reading or modifying
the machine. Please wait for that Vagrant process to end and try
again. Details about the machine are shown below:
ok to test

**Comment by amb26** [comment]
500 error from NPM: default: gyp ERR! stack Error: 500 status code downloading 64-bit node.lib
    default: gyp ERR! stack     at Request.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\lib\install.js:374:20)
ok to test

**Comment by javihernandez** [comment]
ok to test

**Comment by amb26** [comment]
ok to test

**Comment by amb26** [comment]
ok to test

**Comment by amb26** [comment]
ok to test

**Comment by amb26** [comment]
ok to test

**Comment by amb26** [comment]
ok to test

**Comment by amb26** [comment]
ok to test

**Comment by amb26** [comment]
ok to test

**Comment by kaspermarkus** [comment]
ok to test

**Comment by amb26** [comment]
ok to test

**Comment by amb26** [comment]
ok to test

**Comment by amb26** [comment]
Run 1321: Unit test failure: Timed out waiting for language names
````
05:45:26.779:  languageNames failed
05:45:26.780:  ASSERTION FAILED: {
    "isError": true,
    "message": "Timed out waiting for the language names"
}
05:45:26.781:  jq: FAIL: Module "Language tests" Test name "Test getting language names" - Message: Assertion failure (see console.log for expanded message): [object Object]
05:45:26.781:  jq: Source:     at jqUnit.nodeFailureHandler (\\vboxsvr\vagrant\node_modules\node-jqunit\lib\jqUnit-node.js:34:15)
    at Object.fire (\\vboxsvr\vagrant\node_modules\infusion\src\framework\core\js\Fluid.js:1612:40)
    at Array.fluid.fail (\\vboxsvr\vagrant\node_modules\infusion\src\framework\core\js\Fluid.js:222:32)
    at Object.that.complete (\\vboxsvr\vagrant\node_modules\infusion\src\framework\core\js\FluidPromises.js:70:25)
    at Object.that.reject (\\vboxsvr\vagrant\node_modules\infusion\src\framework\core\js\FluidPromises.js:61:22)
    at ChildProcess.<anonymous> (\\vboxsvr\vagrant\gpii\node_modules\gpii-localisation\src\language.js:242:21)
    at ChildProcess.emit (events.js:182:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
````

**Pull request closed without merging**
