### PR TITLE
GPII-3811: Add support for high contrast themes in Wndows 10 1809

### PR DESCRIPTION
**Pull request by stegru**
Makes the custom high-contrast themes work on Windows 10 1809.

More info: https://issues.gpii.net/browse/GPII-3811

### CODE REVIEW

**Comment by javihernandez** [comment]
@stegru, Is this ready to re-review or do you still need to get some more work done before?

**Comment by stegru** [comment]
Cherry-picked @JavierJF's localisation fix (https://github.com/stegru/windows/pull/8), and butchered it to not require universal in the child process and call the process once per language for all themes, and cache the result.

Tested in 1803 and 1903

**Comment by stegru** [comment]
ok to test

**Comment by javihernandez** [comment]
> CI job failed: https://ci.gpii.net/job/windows-tests/1412/

```
Bringing machine 'default' up with 'virtualbox' provider...
Build timed out (after 45 minutes). Marking the build as failed.
Build was aborted
Finished: FAILURE
```
ok to test

**Comment by amb26** [comment]
Total blowout provisioning CI, let's wait until the storm passes

**Comment by javihernandez** [comment]
ok to test

**Pull request merged**
