### PR TITLE
GPII-4152: Onboard Focus related Windows 10 settings

### PR DESCRIPTION
**Pull request by JavierJF**
This pull replaces the old systemSettingsHandler native implementation.

**Warning: Do not merge yet**

The pull introduces new development dependencies we may want to include directly in the vagrant boxes.

### CODE REVIEW

**Comment by JavierJF** [comment]
All CI fails are related to VM provisioning not being able to complete due to the SDK installations required by the pull. This timeout have been increased.

image

**Comment by JavierJF** [comment]
Ok to test

**Comment by stegru** [comment]
I reviewed the wrong PR, see https://github.com/GPII/windows/pull/284#pullrequestreview-319134989 (same code)

**Comment by JavierJF** [comment]
Apparently resolution failed to be set during tests for the VM, the error is non-related to this pull contents:

image

**Comment by JavierJF** [comment]
Ok to test

**Comment by JavierJF** [comment]
Unrelated failure due to AT not being closed:

image

Unrelated failure due to DPI not being set:

image

Testing again.

**Comment by JavierJF** [comment]
Ok to test.

**Comment by JavierJF** [comment]
Unit tests failed again with screen resolution issues as before:

image

Acceptance tests failed with EADDRINUSE failure:

image

Both failures are unrelated to the contents of this pull, homonym pull GPII-4231 passed CI in a build at the same time with the same contents of this pull. Testing again.

**Comment by JavierJF** [comment]
Ok to test

**Comment by amb26** [comment]
Looks like some genuine failures to me:
````
13:36:12.426:  systemSettingsHandler return[{"settingID": "SystemSettings_Accessibility_Narrator_IsAutoStartEnabled", "isError": false, "errorMessage": null, "returnValue": false},{"settingID": "SystemSettings_Accessibility_Narrator_IsAutoStartOnLogonDesktopEnabled", "isError": true, "errorMessage": "Failed to apply setting - ErrorCode: '0x5b4'", "returnValue": null}]
````

**Comment by amb26** [comment]
But let's have another go - ok to test

**Comment by JavierJF** [comment]
@amb26 that's a genuine failure, it's a timeout failure, maybe the system in CI was too exhausted, it's a good indication that we may need to increase that values a little bit.

**Comment by JavierJF** [comment]
Looks like for this build we lost CI as in GPII-2750 at the same time:

image

Testing again.

**Comment by JavierJF** [comment]
Ok to test

**Comment by JavierJF** [comment]
Machine failed to create due to a problem with NPM, testing again:

```
    default: npm ERR! code E404
    default: npm ERR! 404 Not Found: error-ex@^1.3.1
    default: npm ERR! A complete log of this run can be found in:
    default: npm ERR!     C:\Users\vagrant\AppData\Roaming\npm-cache\_logs\2020-02-12T19_11_40_131Z-debug.log
    default: VERBOSE: 'npm' exited with 1
```

**Comment by JavierJF** [comment]
Ok to test.

**Comment by JavierJF** [comment]
Same failure as previously, related to npm issue: https://github.com/facebook/create-react-app/issues/8465. Issue appears to be solved now, so testing again.

**Comment by JavierJF** [comment]
Ok to test.

**Comment by amb26** [comment]
Acceptance tests have failed with the error:
````
0:08:21.079:  Saving theme from C:\Windows\resources\Themes\aero.theme
00:08:21.378:  FATAL ERROR: Uncaught exception: EPERM: operation not permitted, open 'C:\Windows\resources\Themes\aero.theme'
Error: EPERM: operation not permitted, open 'C:\Windows\resources\Themes\aero.theme'
````

**Comment by JavierJF** [comment]
> Acceptance tests have failed with the error:
> 
> ```
> 0:08:21.079:  Saving theme from C:\Windows\resources\Themes\aero.theme
> 00:08:21.378:  FATAL ERROR: Uncaught exception: EPERM: operation not permitted, open 'C:\Windows\resources\Themes\aero.theme'
> Error: EPERM: operation not permitted, open 'C:\Windows\resources\Themes\aero.theme'
> ```

Yes, this error is not related to the pull request, it's present in master and it's solved by #293  by @stegru .

**Comment by JavierJF** [comment]
### Unrelated failures:

Unit tests failure related to processHandling:

```
08:17:06.368:  jq: FAIL: Module "gpii.tests.windows.processHandling" Test name "Testing closeProcessByName" - Message: Expected 3 assertions, but 2 were run
08:17:06.369:  jq: Source:     at Object.asyncTest (\\vboxsvr\vagrant\node_modules\infusion\tests\lib\qunit\js\qunit.js:406:9)
    at Object.<anonymous> (\\vboxsvr\vagrant\gpii\node_modules\processHandling\test\testProcessHandling.js:165:8)
```

```
08:17:06.368:  jq: FAIL: Module "gpii.tests.windows.processHandling" Test name "Testing closeProcessByName" - Message: Expected 3 assertions, but 2 were run
08:17:06.369:  jq: Source:     at Object.asyncTest (\\vboxsvr\vagrant\node_modules\infusion\tests\lib\qunit\js\qunit.js:406:9)
    at Object.<anonymous> (\\vboxsvr\vagrant\gpii\node_modules\processHandling\test\testProcessHandling.js:165:8)
```

```
08:17:07.589:  jq: FAIL: Module "gpii.tests.windows.processHandling" Test name "Testing closeProcessByName (window-less process)" - Message: Expected 3 assertions, but 4 were run
08:17:07.590:  jq: Source:     at Object.asyncTest (\\vboxsvr\vagrant\node_modules\infusion\tests\lib\qunit\js\qunit.js:406:9)
    at Object.<anonymous> (\\vboxsvr\vagrant\gpii\node_modules\processHandling\test\testProcessHandling.js:201:8)
```

AcceptanceTests failure related to spi:

```
08:21:14.830:  jq: FAIL: Module "gpii.tests.acceptance.windows.builtIn.config tests" Test name "Testing os_win using default matchmaker" - Message: Assertion failure (see console.log for expanded message): SpiSettingsHandler.js: spi.applySettings() failed with error code 0.
08:21:14.830:  jq: Source:     at jqUnit.nodeFailureHandler (\\vboxsvr\vagrant\node_modules\node-jqunit\lib\jqUnit-node.js:34:15)
    at Object.fire (\\vboxsvr\vagrant\node_modules\infusion\src\framework\core\js\Fluid.js:1612:40)
    at Object.fluid.fail (\\vboxsvr\vagrant\node_modules\infusion\src\framework\core\js\Fluid.js:222:32)
    at \\vboxsvr\vagrant\gpii\node_modules\spiSettingsHandler\src\SpiSettingsHandler.js:254:27
    at Object.that.then (\\vboxsvr\vagrant\node_modules\infusion\src\framework\core\js\FluidPromises.js:33:21)
    at Object.gpii.windows.spi.applySettings (\\vboxsvr\vagrant\gpii\node_modules\spiSettingsHandler\src\SpiSettingsHandler.js:238:10)
    at gpii.windows.spi.setImpl (\\vboxsvr\vagrant\gpii\node_modules\spiSettingsHandler\src\SpiSettingsHandler.js:414:22)
```
AcceptanceTests failure related to AT closing:

```
08:22:17.320:  jq: FAIL: Module "gpii.tests.acceptance.windows.builtIn.config tests" Test name "Testing os_common - magnifier running on startup" - Message: Checking that settings are properly reset - at sequence position 24 of 30
```

**Comment by JavierJF** [comment]
Ok to test.

**Pull request closed without merging**
