### PR TITLE
GPII-3802: Commenting out app zoom tests which fail fairly often in electron

### PR DESCRIPTION
**Pull request by amb26**

### CODE REVIEW

**Comment by amb26** [comment]
Our old friend SPI nonClientMetrics:
````
09:38:55.910:  jq: FAIL: Module "SpiSettingsHandler Module" Test name "SpiSettingsHandler test - testNonClientMetrics" - Message: Timed out waiting for the SPI call to complete (see GPII-2001)
09:38:55.910:  jq: Source:     at pok (\\vboxsvr\vagrant\node_modules\infusion\tests\test-core\jqUnit\js\jqUnit.js:112:15)
    at Object.fail (\\vboxsvr\vagrant\node_modules\infusion\tests\test-core\jqUnit\js\jqUnit.js:129:13)
    at Array.<anonymous> (\\vboxsvr\vagrant\gpii\node_modules\spiSettingsHandler\test\testSpiSettingsHandler.js:61:24)
    at Object.that.complete (\\vboxsvr\vagrant\node_modules\infusion\src\framework\core\js\FluidPromises.js:70:25)
    at Array.that.reject (\\vboxsvr\vagrant\node_modules\infusion\src\framework\core\js\FluidPromises.js:61:22)
    at Object.that.complete (\\vboxsvr\vagrant\node_modules\infusion\src\framework\core\js\FluidPromises.js:70:25)
    at Array.that.reject (\\vboxsvr\vagrant\node_modules\infusion\src\framework\core\js\FluidPromises.js:61:22)
    at Object.that.complete (\\vboxsvr\vagrant\node_modules\infusion\src\framework\core\js\FluidPromises.js:70:25)
    at Object.that.reject (\\vboxsvr\vagrant\node_modules\infusion\src\framework\core\js\FluidPromises.js:61:22)
    at ChildPro .... [output suppressed at 1024 chars - for more output, increase fluid.logObjectRenderChars]
09:38:55.924:  jq: FAIL: Module "SpiSettingsHandler Module" Test name "SpiSettingsHandler test - testNonClientMetrics" - Message: Expected 7 assertions, but 1 were run
09:38:55.924:  jq: Source:     at Object.asyncTest (\\vboxsvr\vagrant\node_modules\infusion\tests\lib\qunit\js\qunit.js:406:9)
    at \\vboxsvr\vagrant\gpii\node_modules\spiSettingsHandler\test\testSpiSettingsHandler.js:36:12
    at Object.fluid.each (\\vboxsvr\vagrant\node_modules\infusion\src\framework\core\js\Fluid.js:552:17)
    at Object.<anonymous> (\\vboxsvr\vagrant\gpii\node_modules\spiSettingsHandler\test\testSpiSettingsHandler.js:34:7)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Module.replacementCompile (\\vboxsvr\vagrant\node_modules\nyc\node_modules\append-transform\index.js:58:13)
    at Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Object.<anonymous> (\\vboxsvr\vagrant\node_modules\nyc\node_modules\append-transform\index.js:62:4)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader .... [output suppressed at 1024 chars - for more output, increase fluid.logObjectRenderChars]
09:38:55.924:  jq: Test concluded - Module "SpiSettingsHandler Module" Test name "SpiSettingsHandler test - testNonClientMetrics": 0/2 passed - FAIL
````

**Comment by amb26** [comment]
ok to test

**Comment by stegru** [comment]
You touched it last!

**Comment by amb26** [comment]
I've now got this one every one of 4 runs :( And the tests get stuck with fat scrollbars

**Comment by stegru** [comment]
I think it would be reasonable to remove the non-client metrics test, considering the is nothing in the SR that uses it.

A search for `SPI_SETNONCLIENTMETRICS` shows only the work-around for it.

**Pull request merged**
