### PR TITLE
GPII-1108: Fixed logic for allowing deletion of subkeys of nonexistent parents in the registry to be a noop

### PR DESCRIPTION
**Pull request by amb26**

### CODE REVIEW

**Comment by amb26** [comment]
@kaspermarkus - could you take this one on?

**Comment by amb26** [comment]
@kaspermarkus - bump (after 18 months : P )

**Comment by kaspermarkus** [comment]
@amb26 haha, yeah, I guess it'd be about time for me to review it... Currently has conflicts with master, but if you update it, I'll review asap

**Comment by amb26** [comment]
Cheers @kaspermarkus  - all updated now

**Comment by kaspermarkus** [comment]
Looks great and passes everything! Merged!

**Comment by gtirloni** [comment]
ok to test

**Pull request merged**
