### PR TITLE
GPII-3644: Onboard Windows 10 "Device" -> "Mouse" -> "Additional pointer options"

### PR DESCRIPTION
**Pull request by JavierJF**

### CODE REVIEW

**Comment by JavierJF** [comment]
Something weird failed because tests passed. Testing again

image

**Comment by amb26** [comment]
ok to test

**Comment by amb26** [comment]
Hi @JavierJF - I am getting an acceptance test failure with this pull against the most recent universal release which is 0.3.0-dev.20190131T192812Z.7eb9cba7 and should include your universal GPII-3644 pull - do you think you could take a look? Cheers

12:52:27.393:  jq: FAIL: Module "gpii.tests.acceptance.windows.builtIn.config tests" Test name "Testing os_win7 using default matchmaker" - Message: Checking that settings are set

**Comment by JavierJF** [comment]
Hi @amb26! Since new universal version had the changes for the narrator but this pull wasn't updated against master, the settings handled by the systemSettingsHandler failed against current universal, I have updated both branches. After merging locally the new changes a "npm install" for rebuilding the systemSettingsHandler will be necessary. That did the trick and I have tests passing locally now.

**Pull request closed without merging**
